server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "123456"
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 47.120.37.50
    port: 5672
    username: linyun
    password: "123456"
    virtual-host: /
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true